"""Fail-closed identity check for the six files generated by Android CI's SDK step."""
import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
MANIFEST = ROOT / 'tests/fixtures/f04_generated_sdk_identity.json'
MANIFEST_SHA256 = '5667a82f592286be5721679e107c88280ecdf0c898040e540b1c3ee74c97e473'
PATHS = frozenset(
    ['app/src/main/cpp/basssdk/bass.h', 'app/src/main/cpp/basssdk/bassmidi.h'] +
    ['app/src/main/jniLibs/' + abi + '/lib' + library + '.so'
     for abi in ('arm64-v8a', 'armeabi-v7a') for library in ('bass', 'bassmidi')]
)


def verify_generated_sdk(root, untracked):
    """Allow absent SDK on host, or the complete byte-pinned official Android SDK."""
    untracked = set(untracked)
    assert not untracked - PATHS, 'Untracked production source: ' + ', '.join(sorted(untracked - PATHS))
    manifest_bytes = MANIFEST.read_bytes()
    assert hashlib.sha256(manifest_bytes).hexdigest() == MANIFEST_SHA256, 'SDK manifest identity drift'
    manifest = json.loads(manifest_bytes)
    assert manifest['schema'] == 1 and set(manifest['files']) == PATHS, 'SDK manifest path-set drift'
    if not untracked:
        return {}
    assert untracked == PATHS, 'Incomplete generated Android SDK file set'
    verified = {}
    for path in sorted(PATHS):
        file = root / path
        assert file.is_file() and not file.is_symlink(), 'SDK must be a regular file: ' + path
        assert all(not parent.is_symlink() for parent in file.parents if parent != root and root in parent.parents), 'SDK directory symlink: ' + path
        data = file.read_bytes()
        expected = manifest['files'][path]
        actual = hashlib.sha256(data).hexdigest()
        assert len(data) == expected['bytes'] and actual == expected['sha256'], 'Generated Android SDK identity mismatch: ' + path
        verified[path] = actual
    return verified
